version: '3'
services:
    frontend:
        build: images/apache
        image: onyx/ddd-analyzer
        volumes:
            - ..:/var/www/app
            - ../system/bash-history/.frontend:/root/.bash_history
            - ../system/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "${WEB_PORT}:80"
        environment:
            - USER_ID=${USER_ID}
            - GROUP_ID=${GROUP_ID}
